// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzoeunsqfrkrhupbzzlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6b2V1bnNxZnJrcmh1cGJ6emxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODk4NDAsImV4cCI6MjA2OTg2NTg0MH0.dw2aRoNIWDflutQWMrL3PkG8o0P_oErUyKtaWDs4-fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});